name: Build, test and publish
on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
